<?php

global $alphabet;
$alphabet = array(
    'a' => 0,
    'b' =>  1,
    'c' =>  2,
    'd' =>  3,
    'e' =>  4,
    'f' =>  5,
    'g' =>  6,
    'h' =>  7,
    'i' =>  8,
    'j' =>  9,
    'k' => 10,
    'l' => 11,
    'm' => 12,
    'n' => 13,
    'o' => 14,
    'p' => 15,
    'q' => 16,
    'r' => 17,
    's' => 18,
    't' => 19,
    'u' => 20,
    'v' => 21,
    'w' => 22,
    'x' => 23,
    'y' => 24,
    'z' => 25,
);

function shift_cypher_menu () {
    $items['shift_cypher'] = array(
        'title' => 'Use the Shift Cypher!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_form'),
        'access callback' => TRUE,
        'type' =>  MENU_NORMAL_ITEM,
    );

    $items['success'] = array(
        'title' => 'Success',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'shift_success',
    );
    return $items;
}

function shift_form() {
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter a phrase for the cypher.'),
    );

    $form['shift_amount'] = array(
        '#title' => 'Shift Amount',
        '#type' => 'textfield',
        '#description' => t('Please enter a number you want to shift by.'),
        '#element_validate' => array('element_validate_number', 'element_validate_range'),
        '#required' => TRUE,
    );

    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter a direction (left or right) to shift.'),
        '#element_validate' => array('shift_direction_validate'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Use tshe Shift Cypher!',
    );

    return $form;
}

//VALIDATIION
function shift_direction_validate($element, $form_state) {
    $allowed = array('left', 'right', 'Left', 'Right');
    if (!in_array($form_state['values']['shift_direction'], $allowed)) {
        form_set_error('shift_direction', t('Please enter left or right.'));
    }
}

function element_validate_range($element) {
    if ($element['#value'] > 25 || $element['#value'] < 1) {
        form_error($element, t('Number must be less than 26 and greater than 0.'));
    }
}


///END VALIDATIION


///FORM SUBMISSION
function shift_form_submit($form, &$form_state) {
    $alphabet;
    $shift_amt = $form_state['values']['shift_amount'];
    $shift_dir = strtolower($form_state['values']['shift_direction']);
    $shift_phrase = strtolower($form_state['values']['phrase']);
    $shift_phrase = str_split($shift_phrase);
    $result = array();

    foreach ($shift_phrase as $phrase) {
        $phrase = $alphabet[$phrase];

        if ($shift_dir == 'left') {
            $new_spot = $phrase - $shift_amt;
            if ($new_spot > 26) {
                $new_spot = $new_spot + 26;
            }
        } elseif ($shift_dir == 'right') {
            $new_spot = $phrase + $shift_amt;
            if ($new_spot > 26) {
                $new_spot = $new_spot - 26;
            }
        }
        foreach ($alphabet as $key=> $value) {
            if($new_spot == $value) {
                $new_spot = $key;
            }
        }
        array_push($result, $new_spot);
    }
    //session stuff
}

function shift_success() {
    return 'Woo totes worked!';
}
