<?php
function shift_cypher_menu () {
    $items['shift_cypher'] = array(
        'title' => 'Use the Shift Cypher!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_form'),
        'access callback' => TRUE,
        'type' =>  MENU_NORMAL_ITEM,
    );

    $items['success'] = array(
        'title' => 'Success',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'shift_success',
    );
    return $items;
}

function shift_form() {
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter a phrase for the cypher.'),
    );

    $form['shift_amount'] = array(
        '#title' => 'Shift Amount',
        '#type' => 'textfield',
        '#description' => t('Please enter a number you want to shift by.'),
        '#element_validate' => array('element_validate_number', 'element_validate_range'),
        '#required' => TRUE,
    );

    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter a direction (left or right) to shift.'),
        '#element_validate' => array('shift_direction_validate'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Use the Shift Cypher!',
    );

    return $form;
}

function shift_direction_validate($element, $form_state) {
    $allowed = array('left', 'right');
    if (!in_array($form_state['values']['shift_direction'], $allowed)) {
        form_set_error('shift_direction', t('Please enter left or right'));
    }
}

function element_validate_range($element) {
    if ($element['#value'] > 25 || $element['#value'] < 1) {
        form_error($element, t('Number must be less than 26 and greater than 0.'));
    }
}

function shift_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'success';
}

function shift_success() {
    return 'Woo totes worked!';
}
